theme: jekyll-theme-architect
title: Vertex Lighting Plugin Documentation
description: Complete documentation on the Vertex Lighting plugin for Unreal Engine
site_favicon: favicon.ico
search_enabled: true
